apiVersion: apps/v1
kind: Deployment
metadata:
  name: SubscriberMembership
  labels:
    app: SubscriberMembership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SubscriberMembership
  template:
    metadata:
      labels:
        app: SubscriberMembership
    spec:
      containers:
        - name: SubscriberMembership
          image: "username/SubscriberMembership:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
