apiVersion: apps/v1
kind: Deployment
metadata:
  name: PaymentSubscription
  labels:
    app: PaymentSubscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PaymentSubscription
  template:
    metadata:
      labels:
        app: PaymentSubscription
    spec:
      containers:
        - name: PaymentSubscription
          image: "username/PaymentSubscription:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
