apiVersion: v1
kind: Service
metadata:
  name: PaymentSubscription
  labels:
    app: PaymentSubscription
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: PaymentSubscription